# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: ryandemo
# "service" is the name of this project. This will also be added to your AWS resource names.
service: demo-app
frameworkVersion: "4"

custom: 
  stage: ${sls:stage, 'dev'}
  vars: ${file(./config/${sls:stage}.yml)}

provider:
  name: aws
  runtime: nodejs20.x
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com

  environment:
    APP_NAME: ${self:custom.vars.app_name}

functions:
  hello:
    handler: handler.helloWorld
    events:
      - httpApi:
          path: /
          method: get
  welcome:
    handler: handler.welcome
    events: 
      - httpApi:
          path: /welcome
          method: post
  getUser:
    handler: users/user-handler.getUser
    events:
      - httpApi:
          path: /user
          method: get


plugins: 
  - serverless-offline
